<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:brocom="http://www.broservices.nl/xsd/brocommon/3.0"
           xmlns:gml="http://www.opengis.net/gml/3.2"
           xmlns:gmwcom="http://www.broservices.nl/xsd/gmwcommon/1.1"
           xmlns:isgmw="http://www.broservices.nl/xsd/isgmw/1.1"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.broservices.nl/xsd/gmwcommon/1.1"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified"
           version="1.1.0">

   <xs:import namespace="http://www.broservices.nl/xsd/brocommon/3.0"
              schemaLocation="https://schema.broservices.nl/xsd/brocommon/3.0/brocommon.xsd"/>
   <xs:import namespace="http://www.opengis.net/gml/3.2"
              schemaLocation="https://schema.broservices.nl/profile/gml/1.0/gml-profile.xsd"/>

      <xs:complexType name="DeliveredLocationType">
      <xs:sequence>
         <xs:element name="location"
                     type="gml:PointType"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="horizontalPositioningMethod"
                     type="gmwcom:HorizontalPositioningMethodType"
                     minOccurs="1"
                     maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="DeliveredVerticalPositionType">
      <xs:sequence>
         <xs:element name="localVerticalReferencePoint"
                     type="gmwcom:LocalVerticalReferencePointType"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="offset"
                     minOccurs="1"
                     maxOccurs="1"
                     nillable="true">
               <xs:complexType>
                  <xs:simpleContent>
                        <xs:restriction base="brocom:MeasureNillableType">
                           <xs:attribute name="uom"
                                          type="gml:UomIdentifier"
                                          use="required"
                                       fixed="m"/>
                        </xs:restriction>
                  </xs:simpleContent>
               </xs:complexType>
         </xs:element>
         <xs:element name="verticalDatum"
                     type="gmwcom:VerticalDatumType"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="groundLevelPosition"
                     minOccurs="1"
                     maxOccurs="1"
                     nillable="true">
            <xs:complexType>
               <xs:simpleContent>
                  <xs:restriction base="brocom:MeasureNillableType">
                     <xs:attribute name="uom"
                        type="gml:UomIdentifier"
                        use="required"
                        fixed="m" />
                  </xs:restriction>
               </xs:simpleContent>
                     </xs:complexType>
         </xs:element>
         <xs:element name="groundLevelPositioningMethod"
                     type="gmwcom:GroundLevelPositioningMethodType"
                     minOccurs="1"
                     maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="ElectrodeType">
      <xs:sequence>
         <xs:element name="electrodeNumber"
                     type="xs:integer"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="electrodePackingMaterial"
                     type="gmwcom:ElectrodePackingMaterialType"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="electrodeStatus"
                     type="gmwcom:ElectrodeStatusType"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="electrodePosition"
                     minOccurs="1"
                     maxOccurs="1"
                     nillable="true">
               <xs:complexType>
                  <xs:simpleContent>
                        <xs:restriction base="brocom:MeasureNillableType">
                           <xs:attribute name="uom"
                                          type="gml:UomIdentifier"
                                          use="required"
                                       fixed="m"/>
                        </xs:restriction>
                  </xs:simpleContent>
               </xs:complexType>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
      <xs:complexType name="MaterialUsedType">
      <xs:sequence>
         <xs:element name="tubePackingMaterial"
                     type="gmwcom:TubePackingMaterialType"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="tubeMaterial"
                     type="gmwcom:TubeMaterialType"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="glue"
                     type="gmwcom:GlueType"
                     minOccurs="1"
                     maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="InsertedPartType">
      <xs:sequence>
         <xs:element name="insertedPartLength"
                     minOccurs="1"
                     maxOccurs="1"
                     nillable="true">
               <xs:complexType>
                  <xs:simpleContent>
                        <xs:restriction base="brocom:MeasureNillableType">
                           <xs:attribute name="uom"
                                          type="gml:UomIdentifier"
                                          use="required"
                                       fixed="m"/>
                        </xs:restriction>
                  </xs:simpleContent>
               </xs:complexType>
         </xs:element>
         <xs:element name="insertedPartDiameter"
                     minOccurs="1"
                     maxOccurs="1"
                     nillable="true">
               <xs:complexType>
                  <xs:simpleContent>
                        <xs:restriction base="brocom:MeasureNillableType">
                           <xs:attribute name="uom"
                                          type="gml:UomIdentifier"
                                          use="required"
                                       fixed="mm"/>
                        </xs:restriction>
                  </xs:simpleContent>
               </xs:complexType>
         </xs:element>
         <xs:element name="insertedPartMaterial"
                     type="gmwcom:TubeMaterialType"
                     minOccurs="1"
                     maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="SedimentSumpType">
      <xs:sequence>
         <xs:element name="sedimentSumpLength"
                     minOccurs="0"
                     maxOccurs="1"
                     nillable="true">
               <xs:complexType>
                  <xs:simpleContent>
                        <xs:restriction base="brocom:MeasureNillableType">
                           <xs:attribute name="uom"
                                          type="gml:UomIdentifier"
                                          use="required"
                                       fixed="m"/>
                        </xs:restriction>
                  </xs:simpleContent>
               </xs:complexType>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="PlainTubePartType">
      <xs:sequence>
         <xs:element name="plainTubePartLength"
                     minOccurs="0"
                     maxOccurs="1"
                     nillable="true">
               <xs:complexType>
                  <xs:simpleContent>
                        <xs:restriction base="brocom:MeasureNillableType">
                           <xs:attribute name="uom"
                                          type="gml:UomIdentifier"
                                          use="required"
                                       fixed="m"/>
                        </xs:restriction>
                  </xs:simpleContent>
               </xs:complexType>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="TubePackingMaterialType">
      <xs:simpleContent>
         <xs:restriction base="gml:CodeWithAuthorityType">
            <xs:attribute name="codeSpace" type="xs:anyURI" use="required" fixed="urn:bro:gmw:TubePackingMaterial" />
         </xs:restriction>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="GlueType">
      <xs:simpleContent>
         <xs:restriction base="gml:CodeWithAuthorityType">
            <xs:attribute name="codeSpace" type="xs:anyURI" use="required" fixed="urn:bro:gmw:Glue" />
         </xs:restriction>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="TubeMaterialType">
      <xs:simpleContent>
         <xs:restriction base="gml:CodeWithAuthorityType">
            <xs:attribute name="codeSpace" type="xs:anyURI" use="required" fixed="urn:bro:gmw:TubeMaterial" />
         </xs:restriction>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="SockMaterialType">
      <xs:simpleContent>
         <xs:restriction base="gml:CodeWithAuthorityType">
            <xs:attribute name="codeSpace" type="xs:anyURI" use="required" fixed="urn:bro:gmw:SockMaterial" />
         </xs:restriction>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="ElectrodePackingMaterialType">
      <xs:simpleContent>
         <xs:restriction base="gml:CodeWithAuthorityType">
            <xs:attribute name="codeSpace" type="xs:anyURI" use="required" fixed="urn:bro:gmw:ElectrodePackingMaterial" />
         </xs:restriction>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="HorizontalPositioningMethodType">
      <xs:simpleContent>
         <xs:restriction base="gml:CodeWithAuthorityType">
            <xs:attribute name="codeSpace" type="xs:anyURI" use="required" fixed="urn:bro:gmw:HorizontalPositioningMethod" />
         </xs:restriction>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="GroundLevelPositioningMethodType">
      <xs:simpleContent>
         <xs:restriction base="gml:CodeWithAuthorityType">
            <xs:attribute name="codeSpace" type="xs:anyURI" use="required" fixed="urn:bro:gmw:GroundLevelPositioningMethod" />
         </xs:restriction>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="TubeTopPositioningMethodType">
      <xs:simpleContent>
         <xs:restriction base="gml:CodeWithAuthorityType">
            <xs:attribute name="codeSpace" type="xs:anyURI" use="required" fixed="urn:bro:gmw:TubeTopPositioningMethod" />
         </xs:restriction>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="TubeTypeType">
      <xs:simpleContent>
         <xs:restriction base="gml:CodeWithAuthorityType">
            <xs:attribute name="codeSpace" type="xs:anyURI" use="required" fixed="urn:bro:gmw:TubeType" />
         </xs:restriction>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="InitialFunctionType">
      <xs:simpleContent>
         <xs:restriction base="gml:CodeWithAuthorityType">
            <xs:attribute name="codeSpace" type="xs:anyURI" use="required" fixed="urn:bro:gmw:InitialFunction" />
         </xs:restriction>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="ConstructionStandardType">
      <xs:simpleContent>
         <xs:restriction base="gml:CodeWithAuthorityType">
            <xs:attribute name="codeSpace" type="xs:anyURI" use="required" fixed="urn:bro:gmw:ConstructionStandard" />
         </xs:restriction>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="TubeStatusType">
      <xs:simpleContent>
         <xs:restriction base="gml:CodeWithAuthorityType">
            <xs:attribute name="codeSpace" type="xs:anyURI" use="required" fixed="urn:bro:gmw:TubeStatus" />
         </xs:restriction>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="ElectrodeStatusType">
      <xs:simpleContent>
         <xs:restriction base="gml:CodeWithAuthorityType">
            <xs:attribute name="codeSpace" type="xs:anyURI" use="required" fixed="urn:bro:gmw:ElectrodeStatus" />
         </xs:restriction>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="WellStabilityType">
      <xs:simpleContent>
         <xs:restriction base="gml:CodeWithAuthorityType">
            <xs:attribute name="codeSpace" type="xs:anyURI" use="required" fixed="urn:bro:gmw:WellStability" />
         </xs:restriction>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="LocalVerticalReferencePointType">
      <xs:simpleContent>
         <xs:restriction base="gml:CodeWithAuthorityType">
            <xs:attribute name="codeSpace" type="xs:anyURI" use="required" fixed="urn:bro:gmw:LocalVerticalReferencePoint" />
         </xs:restriction>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="DeliveryContextType">
      <xs:simpleContent>
         <xs:restriction base="gml:CodeWithAuthorityType">
            <xs:attribute name="codeSpace" type="xs:anyURI" use="required" fixed="urn:bro:gmw:DeliveryContext" />
         </xs:restriction>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="VerticalDatumType">
      <xs:simpleContent>
         <xs:restriction base="gml:CodeWithAuthorityType">
            <xs:attribute name="codeSpace" type="xs:anyURI" use="required" fixed="urn:bro:gmw:VerticalDatum" />
         </xs:restriction>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="WellHeadProtectorType">
      <xs:simpleContent>
         <xs:restriction base="gml:CodeWithAuthorityType">
            <xs:attribute name="codeSpace" type="xs:anyURI" use="required" fixed="urn:bro:gmw:WellHeadProtector" />
         </xs:restriction>
      </xs:simpleContent>
   </xs:complexType>
   <xs:element name="AbstractRegistrationObject"
               type="brocom:AbstractRegistrationObjectType"
               abstract="true">
      <xs:annotation>
         <xs:documentation source="http://www.imvertor.org/model-info/technical-documentation">Definition: Het geheel van gegevens dat betrekking heeft op een registratieobject en dat in de registratie ondergrond is opgenomen.</xs:documentation>
      </xs:annotation>
   </xs:element>
   <xs:complexType name="AbstractRegistrationObject" abstract="true">
      <xs:complexContent>
         <xs:extension base="brocom:AbstractRegistrationObjectType">
            <xs:sequence>
               <xs:element name="deliveryAccountableParty"
                           type="brocom:OrganizationType"
                           minOccurs="1"
                           maxOccurs="1">
                  <xs:annotation>
                     <xs:documentation source="http://www.imvertor.org/model-info/technical-documentation">Definition: De identificatie die het bestuursorgaan, dat bronhouder is van de gegevens in de basisregistratie ondergrond, als onderneming in het Handelsregister heeft.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="deliveryResponsibleParty"
                           type="brocom:OrganizationType"
                           minOccurs="0"
                           maxOccurs="1">
                  <xs:annotation>
                     <xs:documentation source="http://www.imvertor.org/model-info/technical-documentation">Definition: TODO
Explanation: Het gegeven is door de dataleverancier bij de overdracht meegegeven. Het wordt alleen uitgeleverd aan de dataleverancier en de bronhouder.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="objectIdAccountableParty"
                           minOccurs="0"
                           maxOccurs="1"
                           type="xs:string">
                  <xs:annotation>
                     <xs:documentation source="http://www.imvertor.org/model-info/technical-documentation">Definition: De identificatie die door of voor de bronhouder is gebruikt om het object in de eigen administratie te kunnen vinden, voordat het was geregistreerd in de basisregistratie ondergrond.
Explanation: Het gegeven wordt alleen uitgeleverd aan de dataleverancier en de bronhouder. Het is in de registratie opgenomen om de communicatie tussen de registerbeheerder en de bronhouder of dataleverancier te vergemakkelijken.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="qualityRegime"
                           type="brocom:QualityRegimeType"
                           minOccurs="1"
                           maxOccurs="1">
                  <xs:annotation>
                     <xs:documentation source="http://www.imvertor.org/model-info/technical-documentation">Definition: De aanduiding van de kwaliteitseis waaraan de gegevens van het object voldoen.
Explanation: Het gegeven is door de dataleverancier bij de overdracht meegegeven.</xs:documentation>
                  </xs:annotation>
               </xs:element>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>
   <xs:complexType name="RegistrationObjectPropertyType">
      <xs:sequence minOccurs="0">
         <xs:element ref="brocom:RegistrationObject"/>
      </xs:sequence>
      <xs:attributeGroup ref="gml:AssociationAttributeGroup"/>
   </xs:complexType>
   <xs:element name="BoreholeResearch"
               type="gmwcom:BoreholeResearchType"
               substitutionGroup="gml:AbstractFeature"/>
   <xs:complexType name="BoreholeResearchType">
      <xs:complexContent>
         <xs:extension base="gml:AbstractFeatureType">
            <xs:sequence>
               <xs:element name="broId"
                           type="brocom:RegistrationObjectCodeType"
                           minOccurs="1"
                           maxOccurs="1"/>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>
   <xs:complexType name="BoreholeResearchPropertyType">
      <xs:sequence minOccurs="0">
         <xs:element ref="gmwcom:BoreholeResearch"/>
      </xs:sequence>
      <xs:attributeGroup ref="gml:AssociationAttributeGroup"/>
   </xs:complexType>
   <xs:complexType name="AbstractRegistrationObjectType" abstract="true">
      <xs:complexContent>
         <xs:extension base="gml:AbstractFeatureType">
            <xs:sequence>
               <xs:element name="broId"
                           minOccurs="1"
                           maxOccurs="1"
                           type="brocom:RegistrationObjectCodeType">
                  <xs:annotation>
                     <xs:documentation source="http://www.imvertor.org/model-info/technical-documentation">Definition: Unieke aanduiding van een registratieobject in de basisregistratie ondergrond.</xs:documentation>
                  </xs:annotation>
               </xs:element>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>
   <xs:complexType name="AbstractRegistrationObjectPropertyType">
      <xs:sequence minOccurs="0">
         <xs:element ref="brocom:AbstractRegistrationObject"/>
      </xs:sequence>
      <xs:attributeGroup ref="gml:AssociationAttributeGroup"/>
   </xs:complexType>
      <xs:element name="CoordinateTransformation"
               type="gmwcom:CoordinateTransformationType"/>
   <xs:complexType name="CoordinateTransformationType"/>
   <xs:complexType name="CoordinateTransformationPropertyType">
      <xs:sequence>
         <xs:element ref="gmwcom:CoordinateTransformation"/>
      </xs:sequence>
   </xs:complexType>
   <xs:element name="CRS" type="gmwcom:CRSType"/>
   <xs:complexType name="CRSType"/>
   <xs:complexType name="CRSPropertyType">
      <xs:sequence>
         <xs:element ref="gmwcom:CRS"/>
      </xs:sequence>
   </xs:complexType>
   <xs:element name="EventName" type="gmwcom:EventNameType"/>
   <xs:complexType name="EventNameType"/>
   <xs:complexType name="EventNamePropertyType">
      <xs:sequence>
         <xs:element ref="gmwcom:EventName"/>
      </xs:sequence>
   </xs:complexType>
   <xs:element name="GeotechnicalCPTSurvey"
               type="gmwcom:GeotechnicalCPTSurveyType"
               substitutionGroup="gml:AbstractFeature"/>
      <xs:complexType name="GeotechnicalCPTSurveyType">
      <xs:complexContent>
         <xs:extension base="gml:AbstractFeatureType">
            <xs:sequence>
               <xs:element name="broId"
                           type="brocom:RegistrationObjectCodeType"
                           minOccurs="1"
                           maxOccurs="1"/>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>
   <xs:complexType name="GeotechnicalCPTSurveyPropertyType">
      <xs:sequence minOccurs="0">
         <xs:element ref="gmwcom:GeotechnicalCPTSurvey"/>
      </xs:sequence>
      <xs:attributeGroup ref="gml:AssociationAttributeGroup"/>
   </xs:complexType>
   <xs:element name="GroundwaterMonitoringWell"
               type="gmwcom:GroundwaterMonitoringWellType"/>
   <xs:complexType name="GroundwaterMonitoringWellType">
      <xs:complexContent>
         <xs:extension base="brocom:AbstractRegistrationObjectType">
            <xs:sequence>
               <xs:element name="constructionStandard"
                           type="gmwcom:ConstructionStandardType"
                           minOccurs="1"
                           maxOccurs="1"/>
               <xs:element minOccurs="1"
                           maxOccurs="1"
                           name="deliveredLocation"
                           nillable="false"
                           type="gmwcom:DeliveredLocationType"/>
               <xs:element minOccurs="1"
                           maxOccurs="1"
                           name="deliveredVerticalPosition"
                           nillable="false"
                           type="gmwcom:DeliveredVerticalPositionType"/>
               <xs:element name="deliveryContext"
                           type="gmwcom:DeliveryContextType"
                           minOccurs="1"
                           maxOccurs="1"/>
               <xs:element name="geometricDataPubliclyAvailable"
                           type="brocom:IndicationYesNoType"
                           minOccurs="0"
                           maxOccurs="1"/>
               <xs:element name="groundLevelStable"
                           type="brocom:IndicationYesNoType"
                           minOccurs="1"
                           maxOccurs="1"/>
               <xs:element name="initialFunction"
                           type="gmwcom:InitialFunctionType"
                           minOccurs="1"
                           maxOccurs="1"/>
               <xs:element name="isAbroad"
                           type="brocom:IndicationYesNoType"
                           minOccurs="0"
                           maxOccurs="1"/>
               <xs:element name="maintenanceResponsibleParty"
                           type="brocom:ChamberOfCommerceNumberType"
                           minOccurs="0"
                           maxOccurs="1"/>
               <xs:element minOccurs="1"
                           maxOccurs="unbounded"
                           name="monitoringTube"
                           nillable="false"
                           type="gmwcom:MonitoringTubeType"/>
               <xs:element name="nitgCode"
                           type="xs:string"
                           minOccurs="0"
                           maxOccurs="1"/>
               <xs:element name="numberOfMonitoringTubes"
                           type="xs:integer"
                           minOccurs="1"
                           maxOccurs="1"/>
               <xs:element name="owner" minOccurs="1" maxOccurs="1" nillable="true">
                  <xs:complexType>
                     <xs:simpleContent>
                        <xs:extension base="brocom:ChamberOfCommerceNumberType">
                           <xs:attribute name="nilReason" type="xs:string" use="optional"/>
                        </xs:extension>
                     </xs:simpleContent>
                  </xs:complexType>
               </xs:element>
               <xs:element minOccurs="1"
                           maxOccurs="1"
                           name="registrationHistory"
                           nillable="false"
                           type="brocom:RegistrationHistoryType"/>
               <xs:element name="removed"
                           type="brocom:IndicationYesNoType"
                           minOccurs="1"
                           maxOccurs="1"/>
               <xs:element minOccurs="1"
                           maxOccurs="1"
                           name="standardizedLocation"
                           nillable="false"
                           type="brocom:StandardizedLocationType"/>
               <xs:element name="wellCode"
                           type="gmwcom:WellCodeType"
                           minOccurs="0"
                           maxOccurs="1"/>
               <xs:element name="wellHeadProtector"
                           type="gmwcom:WellHeadProtectorType"
                           minOccurs="1"
                           maxOccurs="1"/>
               <xs:element minOccurs="1"
                           maxOccurs="1"
                           name="wellHistory"
                           nillable="false"
                           type="gmwcom:WellHistoryType"/>
               <xs:element name="wellStability"
                           type="gmwcom:WellStabilityType"
                           minOccurs="0"
                           maxOccurs="1"/>
               <xs:element name="relatedSurvey"
                           type="gmwcom:SurveyPropertyType"
                           minOccurs="0"
                           maxOccurs="unbounded"/>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>
   <xs:complexType name="GroundwaterMonitoringWellPropertyType">
      <xs:sequence minOccurs="0">
         <xs:element ref="gmwcom:GroundwaterMonitoringWell"/>
      </xs:sequence>
      <xs:attributeGroup ref="gml:AssociationAttributeGroup"/>
   </xs:complexType>
   <xs:complexType name="GeoOhmCableType">
      <xs:sequence>
         <xs:element name="cableNumber"
                     type="xs:integer"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="cableInUse"
                     type="brocom:IndicationYesNoUnknownType"
                     minOccurs="0"
                     maxOccurs="1"/>
         <xs:element minOccurs="2"
                     maxOccurs="unbounded"
                     name="electrode"
                     nillable="false"
                     type="gmwcom:ElectrodeType"/>
      </xs:sequence>
   </xs:complexType>
   <xs:element name="IntermediateEvent"
               type="gmwcom:IntermediateEventType"/>
   <xs:complexType name="IntermediateEventType">
         <xs:sequence>
         <xs:element name="eventDate"
                     type="xs:date"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="eventName"
                     type="gmwcom:EventNamePropertyType"
                     minOccurs="1"
                     maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>
   <xs:element name="MonitoringTube"
               type="gmwcom:MonitoringTubeType"/>
   <xs:complexType name="MonitoringTubeType">
      <xs:sequence>
         <xs:element name="tubeNumber"
                     type="xs:integer"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="tubeType"
                     type="gmwcom:TubeTypeType"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="artesianWellCapPresent"
                     type="brocom:IndicationYesNoType"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="sedimentSumpPresent"
                     type="brocom:IndicationYesNoType"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="numberOfGeoOhmCables"
                     type="xs:integer"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="tubeTopDiameter"
                     minOccurs="1"
                     maxOccurs="1"
                     nillable="true">
               <xs:complexType>
                  <xs:simpleContent>
                        <xs:restriction base="brocom:MeasureNillableType">
                           <xs:attribute name="uom"
                                          type="gml:UomIdentifier"
                                          use="required"
                                       fixed="mm"/>
                        </xs:restriction>
                  </xs:simpleContent>
               </xs:complexType>
         </xs:element>
         <xs:element name="variableDiameter"
                     type="brocom:IndicationYesNoType"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="tubeStatus"
                     type="gmwcom:TubeStatusType"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="tubeTopPosition"
                     minOccurs="0"
                     maxOccurs="1"
                     nillable="true">
               <xs:complexType>
                  <xs:simpleContent>
                        <xs:restriction base="brocom:MeasureNillableType">
                           <xs:attribute name="uom"
                                          type="gml:UomIdentifier"
                                          use="required"
                                       fixed="m"/>
                        </xs:restriction>
                  </xs:simpleContent>
               </xs:complexType>
         </xs:element>
         <xs:element name="tubeTopPositioningMethod"
                     type="gmwcom:TubeTopPositioningMethodType"
                     minOccurs="0"
                     maxOccurs="1"/>
         <xs:element name="tubePartInserted"
                     type="brocom:IndicationYesNoType"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="tubeInUse"
                     type="brocom:IndicationYesNoUnknownType"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element minOccurs="1"
                     maxOccurs="1"
                     name="materialUsed"
                     nillable="false"
                     type="gmwcom:MaterialUsedType"/>
         <xs:element minOccurs="1"
                     maxOccurs="1"
                     name="screen"
                     nillable="false"
                     type="gmwcom:ScreenType"/>
         <xs:element minOccurs="1"
                     maxOccurs="1"
                     name="plainTubePart"
                     nillable="false"
                     type="gmwcom:PlainTubePartType"/>
         <xs:element minOccurs="0"
                     maxOccurs="1"
                     name="sedimentSump"
                     nillable="false"
                     type="gmwcom:SedimentSumpType"/>
         <xs:element minOccurs="0"
                     maxOccurs="1"
                     name="insertedPart"
                     nillable="false"
                     type="gmwcom:InsertedPartType"/>
         <xs:element minOccurs="0"
                     maxOccurs="unbounded"
                     name="geoOhmCable"
                     nillable="false"
                     type="gmwcom:GeoOhmCableType"/>
      </xs:sequence>
   </xs:complexType>
   <xs:element name="RegistrationStatus" type="gmwcom:RegistrationStatusType"/>
   <xs:complexType name="RegistrationStatusType"/>
   <xs:complexType name="RegistrationStatusPropertyType">
      <xs:sequence>
         <xs:element ref="gmwcom:RegistrationStatus"/>
      </xs:sequence>
   </xs:complexType>
      <xs:complexType name="ScreenType">
      <xs:sequence>
         <xs:element name="screenLength"
                     minOccurs="0"
                     maxOccurs="1"
                     nillable="true">
               <xs:complexType>
                  <xs:simpleContent>
                        <xs:restriction base="brocom:MeasureNillableType">
                           <xs:attribute name="uom"
                                          type="gml:UomIdentifier"
                                          use="required"
                                       fixed="m"/>
                        </xs:restriction>
                  </xs:simpleContent>
               </xs:complexType>
         </xs:element>
         <xs:element name="screenProtection"
                     type="gmwcom:ScreenProtectionPropertyType"
                     minOccurs="0"
                     maxOccurs="1"/>
         <xs:element name="sockMaterial"
                     type="gmwcom:SockMaterialType"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="screenTopPosition"
                     minOccurs="0"
                     maxOccurs="1"
                     nillable="true">
               <xs:complexType>
                  <xs:simpleContent>
                        <xs:restriction base="brocom:MeasureNillableType">
                           <xs:attribute name="uom"
                                          type="gml:UomIdentifier"
                                          use="required"
                                       fixed="m"/>
                        </xs:restriction>
                  </xs:simpleContent>
               </xs:complexType>
         </xs:element>
         <xs:element name="screenBottomPosition"
                     minOccurs="0"
                     maxOccurs="1"
                     nillable="true">
            <xs:complexType>
               <xs:simpleContent>
                  <xs:restriction base="brocom:MeasureNillableType">
                     <xs:attribute name="uom"
                        type="gml:UomIdentifier"
                        use="required"
                        fixed="m" />
                  </xs:restriction>
               </xs:simpleContent>
                     </xs:complexType>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
      <xs:element name="ScreenProtection" type="gmwcom:ScreenProtectionType"/>
   <xs:complexType name="ScreenProtectionType"/>
   <xs:complexType name="ScreenProtectionPropertyType">
      <xs:sequence>
         <xs:element ref="gmwcom:ScreenProtection"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="StandardizedLocationType">
      <xs:sequence>
         <xs:element name="coordinateTransformation"
                     minOccurs="1"
                     maxOccurs="1"
                     type="brocom:CoordinateTransformationType">
            <xs:annotation>
               <xs:appinfo>
                  <CodeListName>CoordinateTransformation</CodeListName>
                  <CodeListURI>urn:bro:CoordinateTransformation</CodeListURI>
               </xs:appinfo>
               <xs:documentation source="http://www.imvertor.org/model-info/technical-documentation">Definition: De methode die de basisregistratie ondergrond heeft gebruikt voor het omzetten van de aangeleverde coördinaten.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="location"
                     type="gml:PointPropertyType"
                     minOccurs="1"
                     maxOccurs="1">
            <xs:annotation>
               <xs:documentation source="http://www.imvertor.org/model-info/technical-documentation">Definition: De coördinaten in het standaard referentiestelsel.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:element name="Survey" type="gmwcom:SurveyType"/>
   <xs:complexType name="SurveyType">
      <xs:choice minOccurs="1" maxOccurs="1">
         <xs:element ref="gmwcom:BoreholeResearch"/>
         <xs:element ref="gmwcom:GeotechnicalCPTSurvey"/>
      </xs:choice>
   </xs:complexType>
   <xs:complexType name="SurveyPropertyType">
      <xs:sequence minOccurs="0">
         <xs:element ref="gmwcom:Survey"/>
      </xs:sequence>
      <xs:attributeGroup ref="gml:AssociationAttributeGroup"/>
   </xs:complexType>
      <xs:complexType name="WellHistoryType">
      <xs:sequence>
         <xs:element minOccurs="0"
                     maxOccurs="unbounded"
                     name="intermediateEvent"
                     nillable="false"
                     type="gmwcom:IntermediateEventType"/>
         <xs:element name="wellConstructionDate"
                     type="xs:date"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="wellRemovalDate"
                     type="xs:date"
                     minOccurs="0"
                     maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>
   <xs:simpleType name="WellCodeType">
      <xs:restriction base="xs:string"/>
   </xs:simpleType>
</xs:schema>
