<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:brocom="http://www.broservices.nl/xsd/brocommon/3.0"
           xmlns:gml="http://www.opengis.net/gml/3.2"
           xmlns:gmlsf="http://www.opengis.net/gmlsf/2.0"
           xmlns:gmwcom="http://www.broservices.nl/xsd/gmwcommon/1.1"
           xmlns:isgmw="http://www.broservices.nl/xsd/isgmw/1.1"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.broservices.nl/xsd/isgmw/1.1"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified"
           version="1.1.5">
   <xs:annotation>
      <xs:appinfo source="http://schemas.opengis.net/gmlsfProfile/2.0/gmlsfLevels.xsd">
         <gmlsf:ComplianceLevel>0</gmlsf:ComplianceLevel>
      </xs:appinfo>
   </xs:annotation>
   <xs:import namespace="http://www.broservices.nl/xsd/gmwcommon/1.1"
              schemaLocation="gmwcommon.xsd"/>
   <xs:import namespace="http://www.broservices.nl/xsd/brocommon/3.0"
              schemaLocation="brocommon.xsd"/>
   <xs:import namespace="http://www.opengis.net/gml/3.2"
              schemaLocation="gml-profile.xsd"/>
<!--   <xs:import
   namespace="http://www.broservices.nl/xsd/gmwcommon/1.1"
              schemaLocation="https://schema.broservices.nl/xsd/gmwcommon/1.1/gmwcommon.xsd"/>
   <xs:import namespace="http://www.broservices.nl/xsd/brocommon/3.0"
              schemaLocation="https://schema.broservices.nl/xsd/brocommon/3.0/brocommon.xsd"/>
   <xs:import namespace="http://www.opengis.net/gml/3.2"
              schemaLocation="https://schema.broservices.nl/profile/gml/1.0/gml-profile.xsd"/>
              -->
              
   <xs:element name="intakeResponse" type="brocom:IntakeResponseType"/>
   <xs:element name="parseFault" type="brocom:ParseFaultType"/>
   <xs:element name="registrationRequest" type="isgmw:RegistrationRequestType">
      <xs:annotation>
         <xs:documentation source="http://www.imvertor.org/model-info/technical-documentation">Definition: Innameverzoek, dat een dataleverancier (ofwel tevens bronhouder danwel in opdracht van de bronhouder) aanbiedt bij de innameservice van het BRO systeem, waarmee nieuwe gegevens, die net beschikbaar zijn gekomen, aan de BRO worden overdragen.
Explanation: Gegevens over een registratieobject zonder levenscyclus worden eenmalig geregistreerd. Gegevens over een registratieobject met een levenscyclus worden eerst geregistreerd en vervolgens aangevuld en eventueel uiteindelijke beëindigd. Met een correctieverzoek kunnen fouten in geregistreerde gegevens in de BRO worden verbeterd. Verwijderen, of beter het uit registratie nemen van een object is een ingrijpende verandering in de registratie ondergrond, en daartoe kan pas worden besloten na zorgvuldig onderzoek. Het onderzoek begint bij de registratiebeheerder en uiteindelijk kan een object alleen na akkoord van de bronhouder uit registratie genomen worden. Het is bovendien goed om te weten dat de gegevens niet uit de registratie verwijderd worden. De gegevens blijven bestaan maar zijn niet langer voor gebruikers toegankelijk.</xs:documentation>
      </xs:annotation>
   </xs:element>
   <xs:complexType name="RegistrationRequestType">
      <xs:complexContent>
         <xs:extension base="brocom:RegistrationRequestType">
            <xs:sequence>
               <xs:element name="sourceDocument" type="isgmw:SourceDocumentType" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>
   <xs:element name="replaceRequest" type="isgmw:ReplaceRequestType">
      <xs:annotation>
         <xs:documentation source="http://www.imvertor.org/model-info/technical-documentation">Definition: Innameverzoek, dat een dataleverancier (ofwel tevens bronhouder danwel in opdracht van de bronhouder) aanbiedt bij de innameservice van het BRO systeem, waarmee nieuwe gegevens, die net beschikbaar zijn gekomen, aan de BRO worden overdragen.
Explanation: Gegevens over een registratieobject zonder levenscyclus worden eenmalig geregistreerd. Gegevens over een registratieobject met een levenscyclus worden eerst geregistreerd en vervolgens aangevuld en eventueel uiteindelijke beëindigd. Met een correctieverzoek kunnen fouten in geregistreerde gegevens in de BRO worden verbeterd. Verwijderen, of beter het uit registratie nemen van een object is een ingrijpende verandering in de registratie ondergrond, en daartoe kan pas worden besloten na zorgvuldig onderzoek. Het onderzoek begint bij de registratiebeheerder en uiteindelijk kan een object alleen na akkoord van de bronhouder uit registratie genomen worden. Het is bovendien goed om te weten dat de gegevens niet uit de registratie verwijderd worden. De gegevens blijven bestaan maar zijn niet langer voor gebruikers toegankelijk.</xs:documentation>
      </xs:annotation>
   </xs:element>
   <xs:complexType name="ReplaceRequestType">
      <xs:complexContent>
         <xs:extension base="brocom:CorrectionRequestType">
            <xs:sequence>
               <xs:element name="correctionReason" type="isgmw:CorrectionReasonType" minOccurs="1" maxOccurs="1"/>
               <xs:element name="sourceDocument" type="isgmw:SourceDocumentType" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>
   <xs:element name="moveRequest" type="isgmw:MoveRequestType">
      <xs:annotation>
         <xs:documentation source="http://www.imvertor.org/model-info/technical-documentation">Definition: Innameverzoek, dat een dataleverancier (ofwel tevens bronhouder danwel in opdracht van de bronhouder) aanbiedt bij de innameservice van het BRO systeem, waarmee nieuwe gegevens, die net beschikbaar zijn gekomen, aan de BRO worden overdragen.
Explanation: Gegevens over een registratieobject zonder levenscyclus worden eenmalig geregistreerd. Gegevens over een registratieobject met een levenscyclus worden eerst geregistreerd en vervolgens aangevuld en eventueel uiteindelijke beëindigd. Met een correctieverzoek kunnen fouten in geregistreerde gegevens in de BRO worden verbeterd. Verwijderen, of beter het uit registratie nemen van een object is een ingrijpende verandering in de registratie ondergrond, en daartoe kan pas worden besloten na zorgvuldig onderzoek. Het onderzoek begint bij de registratiebeheerder en uiteindelijk kan een object alleen na akkoord van de bronhouder uit registratie genomen worden. Het is bovendien goed om te weten dat de gegevens niet uit de registratie verwijderd worden. De gegevens blijven bestaan maar zijn niet langer voor gebruikers toegankelijk.</xs:documentation>
      </xs:annotation>
   </xs:element>
   <xs:complexType name="MoveRequestType">
      <xs:complexContent>
         <xs:extension base="brocom:CorrectionRequestType">
            <xs:sequence>
               <xs:element name="correctionReason" type="isgmw:CorrectionReasonType" minOccurs="1" maxOccurs="1"/>
               <xs:element name="sourceDocument" type="isgmw:SourceDocumentType" minOccurs="1" maxOccurs="1"/>
               <xs:element name="dateToBeCorrected" type="brocom:PartialDateType" minOccurs="1" maxOccurs="1" />
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>
   <xs:element name="deleteRequest" type="isgmw:DeleteRequestType">
      <xs:annotation>
         <xs:documentation source="http://www.imvertor.org/model-info/technical-documentation">Definition: Innameverzoek, dat een dataleverancier (ofwel tevens bronhouder danwel in opdracht van de bronhouder) aanbiedt bij de innameservice van het BRO systeem, waarmee nieuwe gegevens, die net beschikbaar zijn gekomen, aan de BRO worden overdragen.
Explanation: Gegevens over een registratieobject zonder levenscyclus worden eenmalig geregistreerd. Gegevens over een registratieobject met een levenscyclus worden eerst geregistreerd en vervolgens aangevuld en eventueel uiteindelijke beëindigd. Met een correctieverzoek kunnen fouten in geregistreerde gegevens in de BRO worden verbeterd. Verwijderen, of beter het uit registratie nemen van een object is een ingrijpende verandering in de registratie ondergrond, en daartoe kan pas worden besloten na zorgvuldig onderzoek. Het onderzoek begint bij de registratiebeheerder en uiteindelijk kan een object alleen na akkoord van de bronhouder uit registratie genomen worden. Het is bovendien goed om te weten dat de gegevens niet uit de registratie verwijderd worden. De gegevens blijven bestaan maar zijn niet langer voor gebruikers toegankelijk.</xs:documentation>
      </xs:annotation>
   </xs:element>
      <xs:complexType name="DeleteRequestType">
      <xs:complexContent>
         <xs:extension base="brocom:CorrectionRequestType">
            <xs:sequence>
               <xs:element name="correctionReason" type="isgmw:CorrectionReasonType" minOccurs="1" maxOccurs="1"/>
               <xs:element name="sourceDocument" type="isgmw:SourceDocumentType" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>
   <xs:element name="insertRequest" type="isgmw:InsertRequestType"/>
   <xs:complexType name="InsertRequestType">
      <xs:complexContent>
         <xs:extension base="brocom:CorrectionRequestType">
            <xs:sequence>
               <xs:element name="correctionReason" type="isgmw:CorrectionReasonType" minOccurs="1" maxOccurs="1"/>
               <xs:element name="sourceDocument" type="isgmw:SourceDocumentType" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>
   <xs:element name="GroundwaterMonitoringWell" type="isgmw:GroundwaterMonitoringWellType" substitutionGroup="gml:AbstractFeature"/>   <xs:complexType name="GroundwaterMonitoringWellType">
      <xs:complexContent>
         <xs:extension base="gml:AbstractFeatureType">
            <xs:sequence>
               <xs:element name="deliveryContext"
                           type="gmwcom:DeliveryContextType"
                           minOccurs="1"
                           maxOccurs="1"/>
               <xs:element name="constructionStandard"
                           type="gmwcom:ConstructionStandardType"
                           minOccurs="1"
                           maxOccurs="1"/>
               <xs:element name="initialFunction"
                           type="gmwcom:InitialFunctionType"
                           minOccurs="1"
                           maxOccurs="1"/>
               <xs:element minOccurs="1"
                           maxOccurs="1"
                           name="deliveredLocation"
                           nillable="false"
                           type="gmwcom:DeliveredLocationType"/>
               <xs:element minOccurs="1"
                           maxOccurs="1"
                           name="deliveredVerticalPosition"
                           nillable="false"
                           type="gmwcom:DeliveredVerticalPositionType"/>
               <xs:element name="geometricDataPubliclyAvailable"
                           type="brocom:IndicationYesNoType"
                           minOccurs="0"
                           maxOccurs="1"/>
               <xs:element name="isAbroad"
                           type="brocom:IndicationYesNoType"
                           minOccurs="0"
                           maxOccurs="1"/>
               <xs:element minOccurs="1"
                           maxOccurs="unbounded"
                           name="monitoringTube"
                           nillable="false"
                           type="gmwcom:MonitoringTubeType"/>
               <xs:element name="nitgCode"
                           type="xs:string"
                           minOccurs="0"
                           maxOccurs="1"/>
               <xs:element name="numberOfMonitoringTubes"
                           type="xs:integer"
                           minOccurs="1"
                           maxOccurs="1"/>
               <xs:element name="owner" minOccurs="1" maxOccurs="1" nillable="true">
                  <xs:complexType>
                     <xs:simpleContent>
                        <xs:extension base="brocom:ChamberOfCommerceNumberType">
                           <xs:attribute name="nilReason" type="xs:string" use="optional"/>
                        </xs:extension>
                     </xs:simpleContent>
                  </xs:complexType>
               </xs:element>
               <xs:element minOccurs="1"
                           maxOccurs="1"
                           name="registrationHistory"
                           nillable="false"
                           type="brocom:RegistrationHistoryType"/>
               <xs:element name="removed"
                           type="brocom:IndicationYesNoType"
                           minOccurs="1"
                           maxOccurs="1"/>
               <xs:element minOccurs="1"
                           maxOccurs="1"
                           name="standardizedLocation"
                           nillable="false"
                           type="brocom:StandardizedLocationType"/>
               <xs:element name="wellCode"
                           type="gmwcom:WellCodeType"
                           minOccurs="0"
                           maxOccurs="1"/>
               <xs:element name="wellHeadProtector"
                           type="gmwcom:WellHeadProtectorType"
                           minOccurs="1"
                           maxOccurs="1"/>
               <xs:element minOccurs="1"
                           maxOccurs="1"
                           name="wellHistory"
                           nillable="false"
                           type="gmwcom:WellHistoryType"/>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>
   <xs:complexType name="GroundwaterMonitoringWellPropertyType">
      <xs:sequence minOccurs="0">
         <xs:element ref="isgmw:GroundwaterMonitoringWell"/>
      </xs:sequence>
      <xs:attributeGroup ref="gml:AssociationAttributeGroup"/>
   </xs:complexType>
   <xs:element name="GMW_Construction"
               type="isgmw:GMW_ConstructionType"/>
   <xs:complexType name="GMW_ConstructionType">
            <xs:sequence>
               <xs:element name="objectIdAccountableParty"
                           minOccurs="1"
                           maxOccurs="1"
                           type="xs:string">
                  <xs:annotation>
                     <xs:documentation source="http://www.imvertor.org/model-info/technical-documentation">Definition: De identificatie die door of voor de bronhouder is gebruikt om het object in de eigen administratie te kunnen vinden, voordat het was geregistreerd in de basisregistratie ondergrond.
Explanation: Het gegeven wordt alleen uitgeleverd aan de dataleverancier en de bronhouder. Het is in de registratie opgenomen om de communicatie tussen de registerbeheerder en de bronhouder of dataleverancier te vergemakkelijken.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="deliveryContext"
                           type="gmwcom:DeliveryContextType"
                           minOccurs="1"
                           maxOccurs="1"/>
               <xs:element name="constructionStandard"
                           type="gmwcom:ConstructionStandardType"
                           minOccurs="1"
                           maxOccurs="1"/>
               <xs:element name="initialFunction"
                           type="gmwcom:InitialFunctionType"
                           minOccurs="1"
                           maxOccurs="1"/>
               <xs:element name="numberOfMonitoringTubes"
                           type="xs:integer"
                           minOccurs="1"
                           maxOccurs="1"/>
               <xs:element name="groundLevelStable"
                           type="brocom:IndicationYesNoUnknownType"
                           minOccurs="1"
                           maxOccurs="1"/>
               <xs:element name="wellStability"
                           type="gmwcom:WellStabilityType"
                           minOccurs="0"
                           maxOccurs="1"/>
               <xs:element name="nitgCode"
                           type="xs:string"
                           minOccurs="0"
                           maxOccurs="1"/>
               <xs:element name="owner" minOccurs="1" maxOccurs="1" nillable="true">
                  <xs:complexType>
                     <xs:simpleContent>
                        <xs:extension base="brocom:ChamberOfCommerceNumberType">
                           <xs:attribute name="nilReason" type="xs:string" use="optional"/>
                        </xs:extension>
                     </xs:simpleContent>
                  </xs:complexType>
               </xs:element>
               <xs:element name="maintenanceResponsibleParty"
                           type="brocom:ChamberOfCommerceNumberType"
                           minOccurs="0"
                           maxOccurs="1"/>
               <xs:element name="wellHeadProtector"
                           type="gmwcom:WellHeadProtectorType"
                           minOccurs="1"
                           maxOccurs="1"/>
               <xs:element name="wellConstructionDate"
                           type="brocom:PartialDateType"
                           minOccurs="1"
                           maxOccurs="1"/>
               <xs:element minOccurs="1"
                           maxOccurs="1"
                           name="deliveredLocation"
                           nillable="false"
                           type="gmwcom:DeliveredLocationType"/>
               <xs:element minOccurs="1"
                           maxOccurs="1"
                           name="deliveredVerticalPosition"
                           nillable="false"
                           type="gmwcom:DeliveredVerticalPositionType"/>
               <xs:element minOccurs="1"
                           maxOccurs="unbounded"
                           name="monitoringTube"
                           nillable="false"
                           type="isgmw:MonitoringTubeType"/>
               <xs:element name="geometricDataPubliclyAvailable"
                           type="brocom:IndicationYesNoType"
                           minOccurs="0"
                           maxOccurs="1"/>
               <xs:element name="isAbroad"
                           type="brocom:IndicationYesNoType"
                           minOccurs="0"
                           maxOccurs="1"/>
               <xs:element name="mapSheetCode"
                           minOccurs="0"
                           maxOccurs="1"
                           type="xs:string"/>
               <xs:element name="survey"
                           type="gmwcom:SurveyPropertyType"
                           minOccurs="0"
                           maxOccurs="unbounded"/>
            </xs:sequence>
   </xs:complexType>
   <xs:element name="GMW_ConstructionWithHistory"
               type="isgmw:GMW_ConstructionWithHistoryType"/>
   <xs:complexType name="GMW_ConstructionWithHistoryType">
            <xs:sequence>
               <xs:element minOccurs="1"
                           maxOccurs="1"
                           name="construction"
                           nillable="false"
                           type="isgmw:GMW_ConstructionType"/>
               <xs:element minOccurs="0"
                           maxOccurs="unbounded"
                           name="intermediateEvent"
                           nillable="false"
                           type="isgmw:IntermediateEventsType"/>
               <xs:element name="removal" type="isgmw:GMW_RemovalType" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
   </xs:complexType>
   <xs:complexType name="IntermediateEventsType">
      <xs:sequence>
         <xs:element name="wellHeadProtectorChanged"
                     type="isgmw:SourceDocumentType"
                     minOccurs="0"
                     maxOccurs="1"/>
         <xs:element name="tubeInserted"
                     type="isgmw:SourceDocumentType"
                     minOccurs="0"
                     maxOccurs="1"/>
         <xs:element name="tubeShortenend"
                     type="isgmw:SourceDocumentType"
                     minOccurs="0"
                     maxOccurs="1"/>
         <xs:element name="tubeLengthend"
                     type="isgmw:SourceDocumentType"
                     minOccurs="0"
                     maxOccurs="1"/>
         <xs:element name="tubeStatusChanged"
                     type="isgmw:SourceDocumentType"
                     minOccurs="0"
                     maxOccurs="1"/>
         <xs:element name="ownerChanged"
                     type="isgmw:SourceDocumentType"
                     minOccurs="0"
                     maxOccurs="1"/>
         <xs:element name="electrodeStatusChanged"
                     type="isgmw:SourceDocumentType"
                     minOccurs="0"
                     maxOccurs="1"/>
         <xs:element name="groundLevelShifted"
                     type="isgmw:SourceDocumentType"
                     minOccurs="0"
                     maxOccurs="1"/>
         <xs:element name="newGroundLevelDetermination"
                     type="isgmw:SourceDocumentType"
                     minOccurs="0"
                     maxOccurs="1"/>
         <xs:element name="newPositionsDeterminated"
                     type="isgmw:SourceDocumentType"
                     minOccurs="0"
                     maxOccurs="1"/>
         <xs:element name="newGroundLevelMeasured"
                     type="isgmw:SourceDocumentType"
                     minOccurs="0"
                     maxOccurs="1"/>
         <xs:element name="newPositionsMeasured"
                     type="isgmw:SourceDocumentType"
                     minOccurs="0"
                     maxOccurs="1"/>
         <xs:element name="maintainerChanged"
                     type="isgmw:SourceDocumentType"
                     minOccurs="0"
                     maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>
<xs:complexType name="MonitoringTubeType">
      <xs:sequence>
         <xs:element name="tubeNumber"
                     type="xs:integer"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="tubeType"
                     type="gmwcom:TubeTypeType"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="artesianWellCapPresent"
                     type="brocom:IndicationYesNoUnknownType"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="sedimentSumpPresent"
                     type="brocom:IndicationYesNoUnknownType"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="numberOfGeoOhmCables"
                     type="xs:integer"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="tubeTopDiameter"
                     minOccurs="1"
                     maxOccurs="1"
                     nillable="true">
            <xs:complexType>
               <xs:simpleContent>
                  <xs:restriction base="brocom:MeasureNillableType">
                     <xs:attribute name="uom"
                        type="gml:UomIdentifier"
                        use="required"
                        fixed="mm" />
                  </xs:restriction>
               </xs:simpleContent>
                     </xs:complexType>
         </xs:element>
         <xs:element name="variableDiameter"
                     type="brocom:IndicationYesNoUnknownType"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="tubeStatus"
                     type="gmwcom:TubeStatusType"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="tubeTopPosition"
                     minOccurs="1"
                     maxOccurs="1">
                     <xs:complexType>
                        <xs:simpleContent>
                            <xs:restriction base="brocom:MeasureNillableType">
                                <xs:attribute name="uom"
                                              type="gml:UomIdentifier"
                                              use="required"
                                              fixed="m" />
                            </xs:restriction>
                        </xs:simpleContent>
                    </xs:complexType>
                  </xs:element>
         <xs:element name="tubeTopPositioningMethod"
            type="gmwcom:TubeTopPositioningMethodType"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element minOccurs="1"
            maxOccurs="1"
            name="materialUsed"
            nillable="false"
            type="gmwcom:MaterialUsedType" />
         <xs:element minOccurs="1"
            maxOccurs="1"
            name="screen"
            nillable="false"
            type="gmwcom:ScreenType" />
         <xs:element minOccurs="1"
            maxOccurs="1"
            name="plainTubePart"
            nillable="false"
            type="gmwcom:PlainTubePartType" />
         <xs:element minOccurs="0"
            maxOccurs="1"
            name="sedimentSump"
            nillable="false"
            type="gmwcom:SedimentSumpType" />
         <xs:element minOccurs="0"
            maxOccurs="unbounded"
            name="geoOhmCable"
            nillable="false"
            type="gmwcom:GeoOhmCableType" />
      </xs:sequence>
   </xs:complexType>
   <xs:element name="GMW_Owner"
      type="isgmw:GMW_OwnerType" />
   <xs:complexType name="GMW_OwnerType">
      <xs:sequence>
         <xs:element name="eventDate" type="brocom:PartialDateType" minOccurs="1" maxOccurs="1" />
         <xs:element name="owner" minOccurs="1" maxOccurs="1" nillable="true">
            <xs:complexType>
               <xs:simpleContent>
                  <xs:extension base="brocom:ChamberOfCommerceNumberType">
                     <xs:attribute name="nilReason" type="xs:string" use="optional" />
                  </xs:extension>
               </xs:simpleContent>
            </xs:complexType>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:element name="GMW_WellHeadProtector"
      type="isgmw:GMW_WellHeadProtectorType" />
   <xs:complexType name="GMW_WellHeadProtectorType">
      <xs:sequence>
         <xs:element name="eventDate" type="brocom:PartialDateType" minOccurs="1" maxOccurs="1" />
         <xs:element name="wellHeadProtector"
            type="gmwcom:WellHeadProtectorType"
            minOccurs="1"
            maxOccurs="1" />
      </xs:sequence>
   </xs:complexType>
   <xs:element name="GMW_Lengthening"
      type="isgmw:GMW_LengtheningType" />
   <xs:complexType name="GMW_LengtheningType">
      <xs:sequence>
         <xs:element name="eventDate" type="brocom:PartialDateType" minOccurs="1" maxOccurs="1" />
         <xs:element name="wellHeadProtector"
            type="gmwcom:WellHeadProtectorType"
            minOccurs="0"
            maxOccurs="1" />
         <xs:element name="numberOfTubesLengthened"
            type="xs:integer"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element minOccurs="1"
            maxOccurs="unbounded"
            name="monitoringTube"
            nillable="false"
            type="isgmw:MonitoringTubeLengtheningType" />
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="MonitoringTubeLengtheningType">
      <xs:sequence>
         <xs:element name="tubeNumber"
            type="xs:integer"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element name="tubeTopDiameter"
            minOccurs="0"
            maxOccurs="1"
            nillable="true">
            <xs:complexType>
               <xs:simpleContent>
                  <xs:restriction base="brocom:MeasureNillableType">
                     <xs:attribute name="uom"
                        type="gml:UomIdentifier"
                        use="required"
                        fixed="mm" />
                  </xs:restriction>
               </xs:simpleContent>
            </xs:complexType>
         </xs:element>
         <xs:element name="variableDiameter"
            type="brocom:IndicationYesNoType"
            minOccurs="0"
            maxOccurs="1" />
         <xs:element name="tubeTopPosition"
            minOccurs="1"
            maxOccurs="1"
            nillable="true">
            <xs:complexType>
               <xs:simpleContent>
                  <xs:restriction base="brocom:MeasureNillableType">
                     <xs:attribute name="uom"
                        type="gml:UomIdentifier"
                        use="required"
                        fixed="m" />
                  </xs:restriction>
               </xs:simpleContent>
            </xs:complexType>
         </xs:element>
         <xs:element name="tubeTopPositioningMethod"
            type="gmwcom:TubeTopPositioningMethodType"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element name="tubeMaterial"
            type="gmwcom:TubeMaterialType"
            minOccurs="0"
            maxOccurs="1" />
         <xs:element name="glue"
            type="gmwcom:GlueType"
            minOccurs="0"
            maxOccurs="1" />
         <xs:element name="plainTubePartLength"
            minOccurs="1"
            maxOccurs="1"
            nillable="true">
            <xs:complexType>
               <xs:simpleContent>
                  <xs:restriction base="brocom:MeasureNillableType">
                     <xs:attribute name="uom"
                        type="gml:UomIdentifier"
                        use="required"
                        fixed="m" />
                  </xs:restriction>
               </xs:simpleContent>
            </xs:complexType>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:element name="GMW_GroundLevel"
      type="isgmw:GMW_GroundLevelType" />
   <xs:complexType name="GMW_GroundLevelType">
      <xs:sequence>
         <xs:element name="eventDate" type="brocom:PartialDateType" minOccurs="1" maxOccurs="1" />
         <xs:element name="wellStability"
            type="gmwcom:WellStabilityType"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element name="groundLevelStable"
            type="brocom:IndicationYesNoType"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element name="groundLevelPosition"
            minOccurs="1"
            maxOccurs="1"
            nillable="true">
            <xs:complexType>
               <xs:simpleContent>
                  <xs:restriction base="brocom:MeasureNillableType">
                     <xs:attribute name="uom"
                        type="gml:UomIdentifier"
                        use="required"
                        fixed="m" />
                  </xs:restriction>
               </xs:simpleContent>
            </xs:complexType>
         </xs:element>
         <xs:element name="groundLevelPositioningMethod"
            type="gmwcom:GroundLevelPositioningMethodType"
            minOccurs="1"
            maxOccurs="1" />
      </xs:sequence>
   </xs:complexType>
   <xs:element name="GMW_GroundLevelMeasuring"
      type="isgmw:GMW_GroundLevelMeasuringType" />
   <xs:complexType name="GMW_GroundLevelMeasuringType">
      <xs:sequence>
         <xs:element name="eventDate" type="brocom:PartialDateType" minOccurs="1" maxOccurs="1" />
         <xs:element name="groundLevelPosition"
            minOccurs="1"
            maxOccurs="1"
            nillable="true">
            <xs:complexType>
               <xs:simpleContent>
                  <xs:restriction base="brocom:MeasureNillableType">
                     <xs:attribute name="uom"
                        type="gml:UomIdentifier"
                        use="required"
                        fixed="m" />
                  </xs:restriction>
               </xs:simpleContent>
            </xs:complexType>
         </xs:element>
         <xs:element name="groundLevelPositioningMethod"
            type="gmwcom:GroundLevelPositioningMethodType"
            minOccurs="1"
            maxOccurs="1" />
      </xs:sequence>
   </xs:complexType>
   <xs:element name="GMW_Shortening"
      type="isgmw:GMW_ShorteningType" />
   <xs:complexType name="GMW_ShorteningType">
      <xs:sequence>
         <xs:element name="eventDate" type="brocom:PartialDateType" minOccurs="1" maxOccurs="1" />
         <xs:element name="wellHeadProtector"
            type="gmwcom:WellHeadProtectorType"
            minOccurs="0"
            maxOccurs="1" />
         <xs:element name="numberOfTubesShortened"
            type="xs:integer"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element minOccurs="1"
            maxOccurs="unbounded"
            name="monitoringTube"
            nillable="false"
            type="isgmw:MonitoringTubeShorteningType" />
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="MonitoringTubeShorteningType">
      <xs:sequence>
         <xs:element name="tubeNumber"
            type="xs:integer"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element name="tubeTopPosition"
            minOccurs="1"
            maxOccurs="1">
            <xs:complexType>
               <xs:simpleContent>
                  <xs:restriction base="brocom:MeasureNillableType">
                     <xs:attribute name="uom"
                        type="gml:UomIdentifier"
                        use="required"
                        fixed="m" />
                  </xs:restriction>
               </xs:simpleContent>
            </xs:complexType>
         </xs:element>
         <xs:element name="tubeTopPositioningMethod"
            type="gmwcom:TubeTopPositioningMethodType"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element name="plainTubePartLength"
            minOccurs="1"
            maxOccurs="1">
            <xs:complexType>
               <xs:simpleContent>
                  <xs:restriction base="brocom:MeasureNillableType">
                     <xs:attribute name="uom"
                        type="gml:UomIdentifier"
                        use="required"
                        fixed="m" />
                  </xs:restriction>
               </xs:simpleContent>
            </xs:complexType>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:element name="GMW_ElectrodeStatus"
      type="isgmw:GMW_ElectrodeStatusType" />
   <xs:complexType name="GMW_ElectrodeStatusType">
      <xs:sequence>
         <xs:element name="eventDate" type="brocom:PartialDateType" minOccurs="1" maxOccurs="1" />
         <xs:element name="numberOfElectrodesChanged"
            type="xs:integer"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element minOccurs="1"
            maxOccurs="unbounded"
            name="electrode"
            nillable="false"
            type="isgmw:ElectrodeType" />
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="ElectrodeType">
      <xs:sequence>
         <xs:element name="tubeNumber"
            type="xs:integer"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element name="cableNumber"
            type="xs:integer"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element name="electrodeNumber"
            type="xs:integer"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element name="electrodeStatus"
            type="gmwcom:ElectrodeStatusType"
            minOccurs="1"
            maxOccurs="1" />
      </xs:sequence>
   </xs:complexType>
   <xs:element name="GMW_Positions"
      type="isgmw:GMW_PositionsType" />
   <xs:complexType name="GMW_PositionsType">
      <xs:sequence>
         <xs:element name="eventDate" type="brocom:PartialDateType" minOccurs="1" maxOccurs="1" />
         <xs:element name="wellStability"
            type="gmwcom:WellStabilityType"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element name="groundLevelStable"
            type="brocom:IndicationYesNoType"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element name="numberOfMonitoringTubes"
            type="xs:integer"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element name="groundLevelPosition"
            minOccurs="1"
            maxOccurs="1"
            nillable="true">
            <xs:complexType>
               <xs:simpleContent>
                  <xs:restriction base="brocom:MeasureNillableType">
                     <xs:attribute name="uom"
                        type="gml:UomIdentifier"
                        use="required"
                        fixed="m" />
                  </xs:restriction>
               </xs:simpleContent>
            </xs:complexType>
         </xs:element>
         <xs:element name="groundLevelPositioningMethod"
            type="gmwcom:GroundLevelPositioningMethodType"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element minOccurs="1"
            maxOccurs="unbounded"
            name="monitoringTube"
            nillable="false"
            type="isgmw:MonitoringTubePositionsType" />
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="MonitoringTubePositionsType">
      <xs:sequence>
         <xs:element name="tubeNumber"
            type="xs:integer"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element name="tubeTopPosition"
            minOccurs="1"
            maxOccurs="1">
            <xs:complexType>
               <xs:simpleContent>
                  <xs:restriction base="brocom:MeasureNillableType">
                     <xs:attribute name="uom"
                        type="gml:UomIdentifier"
                        use="required"
                        fixed="m" />
                  </xs:restriction>
               </xs:simpleContent>
            </xs:complexType>
         </xs:element>
         <xs:element name="tubeTopPositioningMethod"
            type="gmwcom:TubeTopPositioningMethodType"
            minOccurs="1"
            maxOccurs="1" />
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="MonitoringTubePositionsMeasuringType">
      <xs:sequence>
         <xs:element name="tubeNumber"
            type="xs:integer"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element name="tubeTopPosition"
            minOccurs="1"
            maxOccurs="1">
            <xs:complexType>
               <xs:simpleContent>
                  <xs:restriction base="brocom:MeasureNillableType">
                     <xs:attribute name="uom"
                        type="gml:UomIdentifier"
                        use="required"
                        fixed="m" />
                  </xs:restriction>
               </xs:simpleContent>
            </xs:complexType>
         </xs:element>
         <xs:element name="tubeTopPositioningMethod"
            type="gmwcom:TubeTopPositioningMethodType"
            minOccurs="1"
            maxOccurs="1" />
      </xs:sequence>
   </xs:complexType>
   <xs:element name="GMW_PositionsMeasuring"
      type="isgmw:GMW_PositionsMeasuringType" />
   <xs:complexType name="GMW_PositionsMeasuringType">
      <xs:sequence>
         <xs:element name="eventDate"
            type="brocom:PartialDateType"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element name="numberOfMonitoringTubes"
            type="xs:integer"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element name="groundLevelPosition"
            minOccurs="0"
            maxOccurs="1">
            <xs:complexType>
               <xs:simpleContent>
                  <xs:restriction base="brocom:MeasureNillableType">
                     <xs:attribute name="uom"
                        type="gml:UomIdentifier"
                        use="required"
                        fixed="m" />
                  </xs:restriction>
               </xs:simpleContent>
            </xs:complexType>
         </xs:element>
         <xs:element name="groundLevelPositioningMethod"
            type="gmwcom:GroundLevelPositioningMethodType"
            minOccurs="0"
            maxOccurs="1" />
         <xs:element minOccurs="1"
            maxOccurs="unbounded"
            name="monitoringTube"
            nillable="false"
            type="isgmw:MonitoringTubePositionsMeasuringType" />
      </xs:sequence>
   </xs:complexType>
   <xs:element name="GMW_Maintainer"
      type="isgmw:GMW_MaintainerType" />
   <xs:complexType name="GMW_MaintainerType">
      <xs:sequence>
         <xs:element name="eventDate" type="brocom:PartialDateType" minOccurs="1" maxOccurs="1" />
         <xs:element name="maintenanceResponsibleParty"
            type="brocom:ChamberOfCommerceNumberType"
            minOccurs="0"
            maxOccurs="1" />
      </xs:sequence>
   </xs:complexType>
   <xs:element name="GMW_TubeStatus"
      type="isgmw:GMW_TubeStatusType" />
   <xs:complexType name="GMW_TubeStatusType">
      <xs:sequence>
         <xs:element name="eventDate" type="brocom:PartialDateType" minOccurs="1" maxOccurs="1" />
         <xs:element name="numberOfTubesChanged"
            type="xs:integer"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element minOccurs="1"
            maxOccurs="unbounded"
            name="monitoringTube"
            nillable="false"
            type="isgmw:MonitoringTubeStatusType" />
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="MonitoringTubeStatusType">
      <xs:sequence>
         <xs:element name="tubeNumber"
            type="xs:integer"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element name="tubeStatus"
            type="gmwcom:TubeStatusType"
            minOccurs="1"
            maxOccurs="1" />
      </xs:sequence>
   </xs:complexType>
   <xs:element name="GMW_Insertion"
      type="isgmw:GMW_InsertionType">
      <xs:annotation>
         <xs:documentation source="http://www.imvertor.org/model-info/technical-documentation">Definition:
            GMW_Insertion</xs:documentation>
      </xs:annotation>
   </xs:element>
   <xs:complexType name="GMW_InsertionType">
      <xs:sequence>
         <xs:element name="tubeNumber"
            type="xs:integer"
            minOccurs="0"
            maxOccurs="1" />
         <xs:element name="eventDate" type="brocom:PartialDateType" minOccurs="1" maxOccurs="1" />
         <xs:element name="tubeTopPosition"
            minOccurs="0"
            maxOccurs="1">
            <xs:complexType>
               <xs:simpleContent>
                  <xs:restriction base="brocom:MeasureNillableType">
                     <xs:attribute name="uom"
                        type="gml:UomIdentifier"
                        use="required"
                        fixed="m" />
                  </xs:restriction>
               </xs:simpleContent>
            </xs:complexType>
         </xs:element>
         <xs:element name="tubeTopPositioningMethod"
            type="gmwcom:TubeTopPositioningMethodType"
            minOccurs="0"
            maxOccurs="1" />
         <xs:element name="insertedPartLength"
            minOccurs="0"
            maxOccurs="1">
            <xs:complexType>
               <xs:simpleContent>
                  <xs:restriction base="brocom:MeasureNillableType">
                     <xs:attribute name="uom"
                        type="gml:UomIdentifier"
                        use="required"
                        fixed="m" />
                  </xs:restriction>
               </xs:simpleContent>
            </xs:complexType>
         </xs:element>
         <xs:element name="insertedPartDiameter"
            minOccurs="0"
            maxOccurs="1">
            <xs:complexType>
               <xs:simpleContent>
                  <xs:restriction base="brocom:MeasureNillableType">
                     <xs:attribute name="uom"
                        type="gml:UomIdentifier"
                        use="required"
                        fixed="mm" />
                  </xs:restriction>
               </xs:simpleContent>
            </xs:complexType>
         </xs:element>
         <xs:element name="insertedPartMaterial"
            type="gmwcom:TubeMaterialType"
            minOccurs="0"
            maxOccurs="1">
            <xs:annotation>
               <xs:documentation source="http://www.imvertor.org/model-info/technical-documentation">Explanation:
                  Het materiaal waaruit de ingeplaatste stijgbuis bestaat.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element minOccurs="0"
            maxOccurs="unbounded"
            name="monitoringTube"
            nillable="false"
            type="isgmw:MonitoringTubeInsertionType" />
         <xs:element name="totalInsertedNumber"
            type="xs:integer"
            minOccurs="0"
            maxOccurs="1" />
      </xs:sequence>
   </xs:complexType>
   <xs:element name="GMW_Shift"
      type="isgmw:GMW_ShiftType" />
   <xs:complexType name="GMW_ShiftType">
      <xs:sequence>
         <xs:element name="eventDate" type="brocom:PartialDateType" minOccurs="1" maxOccurs="1" />
         <xs:element name="groundLevelPosition"
            minOccurs="1"
            maxOccurs="1"
            nillable="true">
            <xs:complexType>
               <xs:simpleContent>
                  <xs:restriction base="brocom:MeasureNillableType">
                     <xs:attribute name="uom"
                        type="gml:UomIdentifier"
                        use="required"
                        fixed="m" />
                  </xs:restriction>
               </xs:simpleContent>
            </xs:complexType>
         </xs:element>
         <xs:element name="groundLevelPositioningMethod"
            type="gmwcom:GroundLevelPositioningMethodType"
            minOccurs="1"
            maxOccurs="1" />
      </xs:sequence>
   </xs:complexType>
   <xs:element name="GMW_Removal"
      type="isgmw:GMW_RemovalType" />
   <xs:complexType name="GMW_RemovalType">
      <xs:sequence>
         <xs:element name="wellRemovalDate"
            type="brocom:PartialDateType"
            minOccurs="1"
            maxOccurs="1" />
      </xs:sequence>
   </xs:complexType>
   <xs:element name="GMW_SubsequentAdditionSurveys"
      type="isgmw:GMW_SubsequentAdditionSurveysType" />
   <xs:complexType name="GMW_SubsequentAdditionSurveysType">
      <xs:sequence>
         <xs:element name="eventDate"
            type="brocom:PartialDateType"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element name="IsRelatedTo"
            type="gmwcom:SurveyType"
            minOccurs="1"
            maxOccurs="unbounded" />
      </xs:sequence>
   </xs:complexType>
   <xs:element name="RegistrationObject"
      type="brocom:AbstractRegistrationObjectType"
      abstract="true"
      substitutionGroup="gml:AbstractFeature">
      <xs:annotation>
         <xs:documentation source="http://www.imvertor.org/model-info/technical-documentation">Definition:
            Het geheel van gegevens dat betrekking heeft op een registratieobject en dat in de
            registratie ondergrond is opgenomen.</xs:documentation>
      </xs:annotation>
   </xs:element>
   <xs:complexType name="RegistrationObjectType" abstract="true">
      <xs:complexContent>
         <xs:extension base="gml:AbstractFeatureType">
            <xs:sequence>
               <xs:element name="deliveryAccountableParty"
                  type="brocom:OrganizationType"
                  minOccurs="1"
                  maxOccurs="1">
                  <xs:annotation>
                     <xs:documentation
                        source="http://www.imvertor.org/model-info/technical-documentation">Definition:
                        De identificatie die het bestuursorgaan, dat bronhouder is van de gegevens
                        in de basisregistratie ondergrond, als onderneming in het Handelsregister
                        heeft.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="deliveryResponsibleParty"
                  type="brocom:OrganizationType"
                  minOccurs="0"
                  maxOccurs="1">
                  <xs:annotation>
                     <xs:documentation
                        source="http://www.imvertor.org/model-info/technical-documentation">Definition:
                        TODO Explanation: Het gegeven is door de dataleverancier bij de overdracht
                        meegegeven. Het wordt alleen uitgeleverd aan de dataleverancier en de
                        bronhouder.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="qualityRegime"
                  type="brocom:QualityRegimeType"
                  minOccurs="1"
                  maxOccurs="1">
                  <xs:annotation>
                     <xs:documentation
                        source="http://www.imvertor.org/model-info/technical-documentation">Definition:
                        De aanduiding van de kwaliteitseis waaraan de gegevens van het object
                        voldoen. Explanation: Het gegeven is door de dataleverancier bij de
                        overdracht meegegeven.</xs:documentation>
                  </xs:annotation>
               </xs:element>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>
   <xs:complexType name="RegistrationObjectPropertyType">
      <xs:sequence minOccurs="0">
         <xs:element ref="brocom:RegistrationObject" />
      </xs:sequence>
      <xs:attributeGroup ref="gml:AssociationAttributeGroup" />
   </xs:complexType>
   <xs:complexType name="MonitoringTubeInsertionType">
      <xs:sequence>
         <xs:element name="insertedPartDiameter"
            minOccurs="1"
            maxOccurs="1">
            <xs:complexType>
               <xs:simpleContent>
                  <xs:restriction base="brocom:MeasureNillableType">
                     <xs:attribute name="uom"
                        type="gml:UomIdentifier"
                        use="required"
                        fixed="mm" />
                  </xs:restriction>
               </xs:simpleContent>
            </xs:complexType>
         </xs:element>
         <xs:element name="insertedPartLength"
            minOccurs="1"
            maxOccurs="1">
            <xs:complexType>
               <xs:simpleContent>
                  <xs:restriction base="brocom:MeasureNillableType">
                     <xs:attribute name="uom"
                        type="gml:UomIdentifier"
                        use="required"
                        fixed="m" />
                  </xs:restriction>
               </xs:simpleContent>
            </xs:complexType>
         </xs:element>
         <xs:element name="insertedPartMaterial"
            type="gmwcom:TubeMaterialType"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element name="tubeNumber"
            type="xs:integer"
            minOccurs="1"
            maxOccurs="1" />
         <xs:element name="tubeTopPosition"
            minOccurs="1"
            maxOccurs="1">
            <xs:complexType>
               <xs:simpleContent>
                  <xs:restriction base="brocom:MeasureNillableType">
                     <xs:attribute name="uom"
                        type="gml:UomIdentifier"
                        use="required"
                        fixed="m" />
                  </xs:restriction>
               </xs:simpleContent>
            </xs:complexType>
         </xs:element>
         <xs:element name="tubeTopPositioningMethod"
            type="gmwcom:TubeTopPositioningMethodType"
            minOccurs="1"
            maxOccurs="1" />
      </xs:sequence>
   </xs:complexType>
   <xs:element name="SourceDocument" type="isgmw:SourceDocumentType" />
   <xs:complexType name="SourceDocumentType">
      <xs:choice minOccurs="1" maxOccurs="1">
         <xs:element ref="isgmw:GMW_Construction" />
         <xs:element ref="isgmw:GMW_ConstructionWithHistory" />
         <xs:element ref="isgmw:GMW_ElectrodeStatus" />
         <xs:element ref="isgmw:GMW_GroundLevel" />
         <xs:element ref="isgmw:GMW_GroundLevelMeasuring" />
         <xs:element ref="isgmw:GMW_Insertion" />
         <xs:element ref="isgmw:GMW_Lengthening" />
         <xs:element ref="isgmw:GMW_Maintainer" />
         <xs:element ref="isgmw:GMW_Owner" />
         <xs:element ref="isgmw:GMW_Positions" />
         <xs:element ref="isgmw:GMW_PositionsMeasuring" />
         <xs:element ref="isgmw:GMW_Removal" />
         <xs:element ref="isgmw:GMW_Shift" />
         <xs:element ref="isgmw:GMW_Shortening" />
         <xs:element ref="isgmw:GMW_SubsequentAdditionSurveys" />
         <xs:element ref="isgmw:GMW_TubeStatus" />
         <xs:element ref="isgmw:GMW_WellHeadProtector" />
      </xs:choice>
   </xs:complexType>
   <xs:element name="Survey" type="isgmw:SurveyType" />
   <xs:complexType name="SurveyType">
      <xs:sequence>
         <xs:element name="boreholeResearch" minOccurs="1" maxOccurs="1">
            <xs:complexType>
               <xs:complexContent>
                  <xs:extension base="gml:AbstractFeatureType">
                     <xs:sequence>
                        <xs:element ref="gmwcom:BoreholeResearch" />
                     </xs:sequence>
                     <xs:attributeGroup ref="gml:AssociationAttributeGroup" />
                  </xs:extension>
               </xs:complexContent>
            </xs:complexType>
         </xs:element>
         <xs:element name="geotechnicalCPTSurvey" minOccurs="1" maxOccurs="1">
            <xs:complexType>
               <xs:complexContent>
                  <xs:extension base="gml:AbstractFeatureType">
                     <xs:sequence>
                        <xs:element ref="gmwcom:GeotechnicalCPTSurvey" />
                     </xs:sequence>
                     <xs:attributeGroup ref="gml:AssociationAttributeGroup" />
                  </xs:extension>
               </xs:complexContent>
            </xs:complexType>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="CorrectionReasonType">
      <xs:simpleContent>
         <xs:restriction base="gml:CodeWithAuthorityType">
            <xs:attribute name="codeSpace" type="xs:anyURI" use="required"
               fixed="urn:bro:gmw:CorrectionReason" />
         </xs:restriction>
      </xs:simpleContent>
   </xs:complexType>
</xs:schema>